name: AITutor
options:
  bundleIdPrefix: com.sansan
settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    BACKEND_BASE_URL: http://192.168.0.102:8000
packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift.git
    from: 2.13.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.7.1
targets:
  AITutor:
    type: application
    platform: iOS
    sources:
      - AITutor
    settings:
      base:
        DEVELOPMENT_TEAM: MKDWSCTD3X
        PRODUCT_BUNDLE_IDENTIFIER: ai.jovida.ha
        INFOPLIST_FILE: AITutor/App/Info.plist
    dependencies:
      - package: LiveKit
      - package: SnapKit
